### ISSUE TITLE
vectorOut does cast from xs to zsVector

### ISSUE THREAD

**Issue by basvdlinden** [luajalla/Experimental#1]
vectorOut does cast from **xs** to zsVector. This should be **zs**.

**Comment by luajalla** [comment]
Hi @basvdlinden 
Thank you for noticing, I've updated the functions and added .net core 3.1 to the list of runtimes.
The benchmark results generated on my laptop are [here](https://github.com/luajalla/Experimental/tree/master/VectorsBmk/BenchmarkResults/results).

Thanks,
Natallie
